site_name: Documentation for Kukos
site_url: https://adrielzera.github.io/Kukos/

nav:
  - Bug Report: index.md
  - Test Case: gherkin.md

theme:
  name: material
  palette:
    - scheme: default
      primary: blue grey
      accent: pink
      toggle:
        icon: material/lightbulb
        name: Modo Claro
    - scheme: slate
      primary: blue grey
      accent: pink
      toggle:
        icon: material/lightbulb-outline
        name: Modo Escuro
  features:
    - navigation.tabs
    - navigation.instant
    - content.code.copy
    - admonition
    - header.autohide

  icon:
    logo: material/rocket-launch

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.betterem
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.emoji

docs_dir: doc-reporting/docs