name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches: 
      - [main]  
      - gh-pages
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install MkDocs and Material theme
        run: pip install mkdocs mkdocs-material

      - name: Build MkDocs site
        run: |
          cd doc-reporting
          mkdocs build --clean

      - name: Deploy MkDocs site
        run: |
          cd doc-reporting
          mkdocs gh-deploy --force

                
