site_name: Documentation for Kukos

on:
  push:
    branches:
      - main  # ou 'master', dependendo da sua branch principal
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Instalar MkDocs
        run: pip install mkdocs
      - name: Instalar tema e plugins (se necessário)
        run: pip install mkdocs-material  # Exemplo, substitua pelo seu tema/plugins
      - name: Construir e implantar o site do MkDocs
        run: mkdocs gh-deploy --force

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/lightbulb
        name: Modo Claro
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/lightbulb-outline
        name: Modo Escuro
  features:
    - navigation.tabs
    - navigation.instant
    - content.code.copy
    - admonition
    - header.autohide

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.betterem
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.emoji